feat: modify CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,10 +32,24 @@ jobs:
           go mod download
           go mod verify
 
-      - name: Install Security Tools
+      - name: Run gosec
         run: |
-          go install github.com/securego/gosec/v2/cmd/gosec@latest
-          go install golang.org/x/vuln/cmd/govulncheck@latest
+          gosec ./...
+          if [ $? -ne 0 ]; then
+            echo "Security audit failed"
+            exit 1
+          fi
+
+      - name: Install govulncheck
+        run: go install golang.org/x/vuln/cmd/govulncheck@latest
+
+      - name: Run govulncheck
+        run: |
+          govulncheck ./...
+          if [ $? -ne 0 ]; then
+            echo "Vulnerability check failed"
+            exit 1
+          fi
 
       - name: Install Linting Tools
         run: |
